alias: "[ Bad - Tür ] LED-Band AN"
description: ""
triggers:
  - type: occupied
    device_id: 69f6efda4d9757d2b57afaa9b2e36367
    entity_id: 0326b4f6d743e0a1ad7630f57cbea2ae
    domain: binary_sensor
    trigger: device
conditions:
  - condition: state
    entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
    state: "off"
actions:
  - service: light.turn_off
    target:
      entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
  - service: light.turn_on
    target:
      entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
    data:
      brightness_pct: 100
      rgb_color: [255, 20, 147]
      transition: 1.5
  - delay: "00:00:00.2"
  - repeat:
      while:
        - condition: state
          entity_id: binary_sensor.anwesenheit_bad
          state: "on"
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
          data:
            brightness_pct: 80
            rgb_color: [255, 20, 147]
            transition: 0.1
        - delay: "00:00:00.1"
        - service: light.turn_on
          target:
            entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
          data:
            brightness_pct: 100
            rgb_color: [255, 20, 147]
            transition: 0.1
        - delay: "00:00:00.3"
        - service: light.turn_on
          target:
            entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
          data:
            brightness_pct: 70
            rgb_color: [255, 20, 147]
            transition: 0.15
        - delay: "00:00:00.15"
        - service: light.turn_on
          target:
            entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
          data:
            brightness_pct: 100
            rgb_color: [255, 20, 147]
            transition: 0.15
        - delay: "00:00:01.0"

  # Nach Beendigung der Wiederholung (keine Bewegung mehr) - Ausschaltvorgang
  - service: light.turn_on
    target:
      entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
    data:
      rgb_color: [0, 255, 0]  # Zu Grün wechseln
      brightness_pct: 100
      transition: 1  # 1 Sekunde für Farbwechsel

  - delay: "00:00:01"  # Warten bis Farbwechsel abgeschlossen

  - service: light.turn_on
    target:
      entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
    data:
      brightness_pct: 1  # Auf 1% runterdimmen
      rgb_color: [0, 255, 0]  # Grün beibehalten
      transition: 1  # 1 Sekunde für Dimmen

  - delay: "00:00:01"  # Warten bis Dimmen abgeschlossen

  - service: light.turn_off  # Komplett ausschalten
    target:
      entity_id: light.paulmann_licht_gmbh_rgb_badezimmer_tuer
mode: single
