alias: "Badezimmer Tür LED Strip - Bewegung erkannt"
description: "Schaltet LED-Strip bei Bewegung mit Herzschlag-Effekt ein und fährt ihn bei Bewegungslosigkeit sanft herunter"
triggers:
  # Trigger: Wird ausgelöst, wenn der Bewegungssensor Besetzt-Status erkennt
  - type: occupied
    device_id: DEINE_BEWEGUNGSSENSOR_DEVICE_ID_HIER  # Durch eigene Device-ID ersetzen
    entity_id: DEINE_BEWEGUNGSSENSOR_ENTITY_ID_HIER  # Durch eigene Entity-ID ersetzen
    domain: binary_sensor
    trigger: device

conditions:
  # Bedingung: LED-Strip muss ausgeschaltet sein, um Doppelauslösungen zu vermeiden
  - condition: state
    entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen
    state: "off"

actions:
  # Sicherstellen, dass das Licht aus ist (Redundanz)
  - service: light.turn_off
    target:
      entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen

  # Sanftes Aufleuchten in Deep Pink (RGB: 255,20,147) über 1.5 Sekunden
  - service: light.turn_on
    target:
      entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen
    data:
      brightness_pct: 100  # Volle Helligkeit
      rgb_color: [255, 20, 147]  # Deep Pink Farbe
      transition: 1.5  # Übergangszeit in Sekunden

  # Kurze Pause vor Start des Herzschlag-Effekts
  - delay: "00:00:00.2"

  # Herzschlag-Effekt - Läuft solange Bewegung erkannt wird
  - repeat:
      while:
        - condition: state
          entity_id: binary_sensor.dein_bewegungssensor  # Durch eigene Entity-ID ersetzen
          state: "on"
      sequence:
        # Erster Puls: Schnelles Abdunkeln auf 80%
        - service: light.turn_on
          target:
            entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen
          data:
            brightness_pct: 80
            rgb_color: [255, 20, 147]
            transition: 0.1
        
        - delay: "00:00:00.1"
        
        # Zurück zur vollen Helligkeit
        - service: light.turn_on
          target:
            entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen
          data:
            brightness_pct: 100
            rgb_color: [255, 20, 147]
            transition: 0.1
        
        - delay: "00:00:00.3"
        
        # Zweiter Puls: Etwas stärkeres Abdunkeln auf 70%
        - service: light.turn_on
          target:
            entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen
          data:
            brightness_pct: 70
            rgb_color: [255, 20, 147]
            transition: 0.15
        
        - delay: "00:00:00.15"
        
        # Zurück zur vollen Helligkeit
        - service: light.turn_on
          target:
            entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen
          data:
            brightness_pct: 100
            rgb_color: [255, 20, 147]
            transition: 0.15
        
        # Pause zwischen den Herzschlägen
        - delay: "00:00:01.0"

  # --- AUSSCHALTVORGANG bei Bewegungslosigkeit ---
  
  # Farbwechsel von Deep Pink zu Grün über 1 Sekunde
  - service: light.turn_on
    target:
      entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen
    data:
      rgb_color: [0, 255, 0]  # Grün
      brightness_pct: 100
      transition: 1  # 1 Sekunde Übergang

  # Warten bis Farbwechsel abgeschlossen ist
  - delay: "00:00:01"

  # Langsames Abdimmen auf 1% Helligkeit über 1 Sekunde
  - service: light.turn_on
    target:
      entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen
    data:
      brightness_pct: 1
      rgb_color: [0, 255, 0]  # Grün beibehalten
      transition: 1  # 1 Sekunde Übergang

  # Warten bis Dimmen abgeschlossen ist
  - delay: "00:00:01"

  # Komplettes Ausschalten des LED-Strips
  - service: light.turn_off
    target:
      entity_id: light.dein_led_strip_entity_id  # Durch eigene Entity-ID ersetzen

mode: single  # Einmalige Ausführung, auch wenn Trigger mehrfach ausgelöst wird
